### PR TITLE
#24 Refactored Clearing of Secrets File

### PR DESCRIPTION
**Pull request by MisterJames**
- extracted write to separate method
- made the call to clear just pass in an empty JObject

Builds and all existing tests are passing. This is essentially a refactor of the private methods; I don't believe a new test is required. This should be resolved, please let me know if you have any feedback.

#24

### CODE REVIEW

**Comment by kichalla** [comment]
:shipit: 

cc: @BrennanConroy

**Comment by BrennanConroy** [comment]
Could you remove WriteSecretFile from ClearSecretFile and then use ClearSecretFile in ProcessSecretFile?

**Comment by MisterJames** [comment]
@BrennanConroy I could, though I guess I thought this was more explicit as I can call "process" or "clear" and know what is happening. The other calls to `ProcessSecretFile` seemed to be more 'doing something with the secrets' versus just clearing the file.

Would you prefer I try do it through the observer (beefing up the JSON file loading for mal-formatted exceptions), or just add another optional param (and introduce a conditional path in 'ProcessSecretFile')? Or any other suggestions...I'm open to whichever.

Cheers.

**Comment by BrennanConroy** [comment]
After another look, this looks good.

**Pull request merged**
