### PR TITLE
Fixing CI failure

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
Looks like a dependency changed and this repo is no longer pulling in System.Reflection.Extensions. cc @rynowak \ @Eilon since I have no idea who owns the repo

**Comment by Eilon** [comment]
Weird, but :shipit:

**Comment by rynowak** [comment]
:shipit:

**Comment by rynowak** [comment]
@eilon this also came up for Testing. My guess is that a CLR package was pulling this in, and has changed to not pull it in.

**Comment by halter73** [comment]
You beat me by 2 minutes https://github.com/aspnet/UserSecrets/pull/50 :angry:

**Comment by pranavkm** [comment]
@halter73 doesn't help that your title was incorrect.

**Comment by Eilon** [comment]
Hah!

**Comment by halter73** [comment]
If only github still didn't track title changes...

**Pull request merged**
